# Site settings
title: Poppy Project

default_title:
  en: "Poppy Project: collaborative ecosystem for robotics"
  fr: "Poppy Project : écosystème collaboratif pour la robotique"

description:
  en: "Poppy Project description."
  fr: "Description du Projet Poppy."

# Build settings
# analytics: true
markdown: kramdown

kramdown:
  syntax_highlighter_opts:
    disable: true

permalink: /:categories/posts/:title
timezone: Europe/Paris

include: [ "_pages" ]

exclude: [
  "Rakefile",
  "bower_components",
  "vendor",
  "README.md",
  "LICENSE.md",
  "CONTRIBUTING.md",
  "Gemfile",
  "Gemfile.lock"
]

default_lang: en

languages:
  - name: English
    key: en
  - name: Français
    key: fr

# Will be overridden by github
github:
  repository_url: https://github.com/poppy-project/poppy-project.org

# HTML compression
compress_html:
  endings: []
  startings: []

# prose.io
prose:
  siteurl: https://www.poppy-project.org/
  relativeLinks: http://prose.github.io/starter/links.jsonp
  media: assets
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - /_script
    - /_sass
    - /css
    - /_posts/.gitkeep
    - .gitignore
    - .scss-lint.yml
    - .travis.yml
    - CONTRIBUTING.yml
    - 404.md
    - Gemfile
    - Gemfile.lock
    - LICENSE.md
    - README.md
    - Rakefile
    - feed.en.xml
    - feed.fr.xml
    - robots.txt
    - index.html
  metadata:
    _posts:
      - name: layout
        field:
          element: hidden
          value: single-column-cover
      - name: lang
        field:
          element: select
          label: Post Language
          options:
            - name: Français
              value: fr
            - name: English
              value: en
      - name: title
        field:
          element: text
          label: Set post title
          help: A post title that should not exceed 60 characters
      - name: description
        field:
          element: text
          label: Set Post description
          help: A post description should be a good summary of the content. Its length should be around 155 characters to be displayed properly in SERP.
      - name: cover_title
        field:
          element: text
          label: Set Cover Title
          help: This text is the main title of the post and is displayed over the cover image
      - name: cover_image
        field:
          element: text
          label: Set Cover Image path
          placeholder: /assets/img/covers/rpi3-lego.jpg
      - name: cover_gradient
        field:
          element: checkbox
          label: Add cover gradient
          help: Adds a dark background to improve cover title readability
          value: false
      - name: cover_size
        field:
          element: select
          label: Cover size
          options:
            - name: Normal
              value: normal
            - name: Small
              value: small

    _pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
